# Generated by Django 4.2.10 on 2024-06-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_rename_itemzzz_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
