# Generated by Django 4.2.10 on 2024-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://order.foodworks.org/assets/img/foodworks/default-menu-image-placeholder.png', max_length=500),
        ),
    ]
